apiVersion: v1
kind: Pod
metadata:
  name: 2node-16gpu-node0
  labels:
    app: gpu-workstation
    cluster: "2node-16gpu"
    node-idx: "0"
    gpu-count: "8"
spec:
  nodeSelector:
    kubernetes.io/hostname: "ip-172-31-129-163.us-west-2.compute.internal"  # 你需要替换为实际的节点hostname
  containers:
  - name: workstation
    image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel  # 或者使用最新版本
    imagePullPolicy: Always
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "1000Gi"
        cpu: "90"
        nvidia.com/gpu: "8"
      limits:
        memory: "1Ti"
        cpu: "95"
        nvidia.com/gpu: "8"
    volumeMounts:
    - name: efs-storage
      mountPath: /home
    - name: dshm
      mountPath: /dev/shm
    env:
    - name: CUDA_VISIBLE_DEVICES
      value: "0,1,2,3,4,5,6,7"
    - name: PYTHONPATH
      value: "/home/efs/connect_to_cluster"
    - name: NODE_RANK
      value: "0"
    - name: WORLD_SIZE
      value: "2"
    - name: MASTER_ADDR
      value: "2node-16gpu-node0"  # 主节点地址
    - name: MASTER_PORT
      value: "29500"
    workingDir: /home/efs/
    tty: true
    stdin: true
    ports:
    - containerPort: 29500
      name: master-port
      protocol: TCP
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: fsx
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 128Gi  # 增加共享内存以支持分布式训练
  restartPolicy: Never
  hostNetwork: false  # 使用Pod网络，便于服务发现
  dnsPolicy: ClusterFirst
